services:
  - type: static
    name: cooper
    buildCommand: npm install && node ./node_modules/vite/bin/vite.js build
    staticPublishPath: dist
    routes:
      - path: "/*"
        destination: /index.html
